google:
  project_id: "gamepicker-e32e9"
  sheets:
    sheet_id: "1FYL7O7RUkm4Fw-D2xw4R48QbY90hKf34oWgZ0_89vX8"
    data_range: "Data"
    user_range: "id-mapping"
    yo_range: "yo-count"
    end_row_title: "SUM"
  secrets:
    MONGO_TOKEN: ARBITRAGEXIV_MONGO_TOKEN
    BOT_TOKEN: BOT_TOKEN

discord:
  server_id: 141695517246750720
  channel_id: 141695517246750720
  wordle_app_user_id: 1211781489931452447

dev:
  server_id: 1106152112557146152
  channel_id: 1199661961907019786
  wordle_app_user_id: 140155378137694208 # personal user id
